version: '3.9'

services:
  main:
    container_name: digi_main
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
      - redis
    env_file:
      - .env
    ports:
      - "${MAIN_PORT}:${MAIN_PORT}"

  mongodb:
    container_name: digi_mongodb
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME= ${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD= ${MONGODB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - data:/data/mongodb

  redis:
    container_name: digi_redis
    image: redis:alpine

volumes:
  data:
