version: '3.9'

services:
  main:
    container_name: digi_main
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
      - redis
    env_file:
      - .env
    ports:
      - "${MAIN_PORT}:${MAIN_PORT}"

  mongodb:
    container_name: digi_mongodb
    image: bitnami/mongodb:4.4.9
    environment:
      - MONGODB_ROOT_USER=${MONGODB_USER}
      - MONGODB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_USERNAME=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - data:/bitnami/mongodb/data

  redis:
    container_name: digi_redis
    image: redis:alpine

volumes:
  data:
    driver: local
